# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mssjo/Code/katelistings

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mssjo/Code/katelistings

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mssjo/Code/katelistings/CMakeFiles /home/mssjo/Code/katelistings/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mssjo/Code/katelistings/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named map_languages

# Build rule for target.
map_languages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 map_languages
.PHONY : map_languages

# fast build rule for target.
map_languages/fast:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/build
.PHONY : map_languages/fast

#=============================================================================
# Target rules for targets named katelistings

# Build rule for target.
katelistings: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 katelistings
.PHONY : katelistings

# fast build rule for target.
katelistings/fast:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/build
.PHONY : katelistings/fast

lib/util/src/char_utils.o: lib/util/src/char_utils.cpp.o

.PHONY : lib/util/src/char_utils.o

# target to build an object file
lib/util/src/char_utils.cpp.o:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/lib/util/src/char_utils.cpp.o
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/lib/util/src/char_utils.cpp.o
.PHONY : lib/util/src/char_utils.cpp.o

lib/util/src/char_utils.i: lib/util/src/char_utils.cpp.i

.PHONY : lib/util/src/char_utils.i

# target to preprocess a source file
lib/util/src/char_utils.cpp.i:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/lib/util/src/char_utils.cpp.i
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/lib/util/src/char_utils.cpp.i
.PHONY : lib/util/src/char_utils.cpp.i

lib/util/src/char_utils.s: lib/util/src/char_utils.cpp.s

.PHONY : lib/util/src/char_utils.s

# target to generate assembly for a file
lib/util/src/char_utils.cpp.s:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/lib/util/src/char_utils.cpp.s
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/lib/util/src/char_utils.cpp.s
.PHONY : lib/util/src/char_utils.cpp.s

lib/util/src/dom_element.o: lib/util/src/dom_element.cpp.o

.PHONY : lib/util/src/dom_element.o

# target to build an object file
lib/util/src/dom_element.cpp.o:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/lib/util/src/dom_element.cpp.o
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/lib/util/src/dom_element.cpp.o
.PHONY : lib/util/src/dom_element.cpp.o

lib/util/src/dom_element.i: lib/util/src/dom_element.cpp.i

.PHONY : lib/util/src/dom_element.i

# target to preprocess a source file
lib/util/src/dom_element.cpp.i:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/lib/util/src/dom_element.cpp.i
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/lib/util/src/dom_element.cpp.i
.PHONY : lib/util/src/dom_element.cpp.i

lib/util/src/dom_element.s: lib/util/src/dom_element.cpp.s

.PHONY : lib/util/src/dom_element.s

# target to generate assembly for a file
lib/util/src/dom_element.cpp.s:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/lib/util/src/dom_element.cpp.s
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/lib/util/src/dom_element.cpp.s
.PHONY : lib/util/src/dom_element.cpp.s

lib/util/src/file_parser.o: lib/util/src/file_parser.cpp.o

.PHONY : lib/util/src/file_parser.o

# target to build an object file
lib/util/src/file_parser.cpp.o:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/lib/util/src/file_parser.cpp.o
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/lib/util/src/file_parser.cpp.o
.PHONY : lib/util/src/file_parser.cpp.o

lib/util/src/file_parser.i: lib/util/src/file_parser.cpp.i

.PHONY : lib/util/src/file_parser.i

# target to preprocess a source file
lib/util/src/file_parser.cpp.i:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/lib/util/src/file_parser.cpp.i
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/lib/util/src/file_parser.cpp.i
.PHONY : lib/util/src/file_parser.cpp.i

lib/util/src/file_parser.s: lib/util/src/file_parser.cpp.s

.PHONY : lib/util/src/file_parser.s

# target to generate assembly for a file
lib/util/src/file_parser.cpp.s:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/lib/util/src/file_parser.cpp.s
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/lib/util/src/file_parser.cpp.s
.PHONY : lib/util/src/file_parser.cpp.s

lib/util/src/file_utils.o: lib/util/src/file_utils.cpp.o

.PHONY : lib/util/src/file_utils.o

# target to build an object file
lib/util/src/file_utils.cpp.o:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/lib/util/src/file_utils.cpp.o
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/lib/util/src/file_utils.cpp.o
.PHONY : lib/util/src/file_utils.cpp.o

lib/util/src/file_utils.i: lib/util/src/file_utils.cpp.i

.PHONY : lib/util/src/file_utils.i

# target to preprocess a source file
lib/util/src/file_utils.cpp.i:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/lib/util/src/file_utils.cpp.i
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/lib/util/src/file_utils.cpp.i
.PHONY : lib/util/src/file_utils.cpp.i

lib/util/src/file_utils.s: lib/util/src/file_utils.cpp.s

.PHONY : lib/util/src/file_utils.s

# target to generate assembly for a file
lib/util/src/file_utils.cpp.s:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/lib/util/src/file_utils.cpp.s
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/lib/util/src/file_utils.cpp.s
.PHONY : lib/util/src/file_utils.cpp.s

map_languages.o: map_languages.cpp.o

.PHONY : map_languages.o

# target to build an object file
map_languages.cpp.o:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/map_languages.cpp.o
.PHONY : map_languages.cpp.o

map_languages.i: map_languages.cpp.i

.PHONY : map_languages.i

# target to preprocess a source file
map_languages.cpp.i:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/map_languages.cpp.i
.PHONY : map_languages.cpp.i

map_languages.s: map_languages.cpp.s

.PHONY : map_languages.s

# target to generate assembly for a file
map_languages.cpp.s:
	$(MAKE) -f CMakeFiles/map_languages.dir/build.make CMakeFiles/map_languages.dir/map_languages.cpp.s
.PHONY : map_languages.cpp.s

src/context.o: src/context.cpp.o

.PHONY : src/context.o

# target to build an object file
src/context.cpp.o:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/context.cpp.o
.PHONY : src/context.cpp.o

src/context.i: src/context.cpp.i

.PHONY : src/context.i

# target to preprocess a source file
src/context.cpp.i:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/context.cpp.i
.PHONY : src/context.cpp.i

src/context.s: src/context.cpp.s

.PHONY : src/context.s

# target to generate assembly for a file
src/context.cpp.s:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/context.cpp.s
.PHONY : src/context.cpp.s

src/context_stack.o: src/context_stack.cpp.o

.PHONY : src/context_stack.o

# target to build an object file
src/context_stack.cpp.o:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/context_stack.cpp.o
.PHONY : src/context_stack.cpp.o

src/context_stack.i: src/context_stack.cpp.i

.PHONY : src/context_stack.i

# target to preprocess a source file
src/context_stack.cpp.i:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/context_stack.cpp.i
.PHONY : src/context_stack.cpp.i

src/context_stack.s: src/context_stack.cpp.s

.PHONY : src/context_stack.s

# target to generate assembly for a file
src/context_stack.cpp.s:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/context_stack.cpp.s
.PHONY : src/context_stack.cpp.s

src/language.o: src/language.cpp.o

.PHONY : src/language.o

# target to build an object file
src/language.cpp.o:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/language.cpp.o
.PHONY : src/language.cpp.o

src/language.i: src/language.cpp.i

.PHONY : src/language.i

# target to preprocess a source file
src/language.cpp.i:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/language.cpp.i
.PHONY : src/language.cpp.i

src/language.s: src/language.cpp.s

.PHONY : src/language.s

# target to generate assembly for a file
src/language.cpp.s:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/language.cpp.s
.PHONY : src/language.cpp.s

src/latex_highlight.o: src/latex_highlight.cpp.o

.PHONY : src/latex_highlight.o

# target to build an object file
src/latex_highlight.cpp.o:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/latex_highlight.cpp.o
.PHONY : src/latex_highlight.cpp.o

src/latex_highlight.i: src/latex_highlight.cpp.i

.PHONY : src/latex_highlight.i

# target to preprocess a source file
src/latex_highlight.cpp.i:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/latex_highlight.cpp.i
.PHONY : src/latex_highlight.cpp.i

src/latex_highlight.s: src/latex_highlight.cpp.s

.PHONY : src/latex_highlight.s

# target to generate assembly for a file
src/latex_highlight.cpp.s:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/latex_highlight.cpp.s
.PHONY : src/latex_highlight.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/rule.o: src/rule.cpp.o

.PHONY : src/rule.o

# target to build an object file
src/rule.cpp.o:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/rule.cpp.o
.PHONY : src/rule.cpp.o

src/rule.i: src/rule.cpp.i

.PHONY : src/rule.i

# target to preprocess a source file
src/rule.cpp.i:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/rule.cpp.i
.PHONY : src/rule.cpp.i

src/rule.s: src/rule.cpp.s

.PHONY : src/rule.s

# target to generate assembly for a file
src/rule.cpp.s:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/rule.cpp.s
.PHONY : src/rule.cpp.s

src/style.o: src/style.cpp.o

.PHONY : src/style.o

# target to build an object file
src/style.cpp.o:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/style.cpp.o
.PHONY : src/style.cpp.o

src/style.i: src/style.cpp.i

.PHONY : src/style.i

# target to preprocess a source file
src/style.cpp.i:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/style.cpp.i
.PHONY : src/style.cpp.i

src/style.s: src/style.cpp.s

.PHONY : src/style.s

# target to generate assembly for a file
src/style.cpp.s:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/style.cpp.s
.PHONY : src/style.cpp.s

src/test.o: src/test.cpp.o

.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i

.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s

.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) -f CMakeFiles/katelistings.dir/build.make CMakeFiles/katelistings.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... katelistings"
	@echo "... map_languages"
	@echo "... lib/util/src/char_utils.o"
	@echo "... lib/util/src/char_utils.i"
	@echo "... lib/util/src/char_utils.s"
	@echo "... lib/util/src/dom_element.o"
	@echo "... lib/util/src/dom_element.i"
	@echo "... lib/util/src/dom_element.s"
	@echo "... lib/util/src/file_parser.o"
	@echo "... lib/util/src/file_parser.i"
	@echo "... lib/util/src/file_parser.s"
	@echo "... lib/util/src/file_utils.o"
	@echo "... lib/util/src/file_utils.i"
	@echo "... lib/util/src/file_utils.s"
	@echo "... map_languages.o"
	@echo "... map_languages.i"
	@echo "... map_languages.s"
	@echo "... src/context.o"
	@echo "... src/context.i"
	@echo "... src/context.s"
	@echo "... src/context_stack.o"
	@echo "... src/context_stack.i"
	@echo "... src/context_stack.s"
	@echo "... src/language.o"
	@echo "... src/language.i"
	@echo "... src/language.s"
	@echo "... src/latex_highlight.o"
	@echo "... src/latex_highlight.i"
	@echo "... src/latex_highlight.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/rule.o"
	@echo "... src/rule.i"
	@echo "... src/rule.s"
	@echo "... src/style.o"
	@echo "... src/style.i"
	@echo "... src/style.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

